ssc = Sub(sub="Cheese", size=large, price=7.95)
ssi = Sub(sub="Italian", size=large, price=7.95)
sshc = Sub(sub="Ham + Cheese", size=large, price=7.95)
ssm = Sub(sub="Meatball", size=large, price=7.95)
sstuna = Sub(sub="Tuna", size=large, price=7.95)
ssturkey = Sub(sub="Turkey", size=large, price=8.50)
sschick = Sub(sub="Chicken Parmigiana", size=large, price=8.50)
ssegg = Sub(sub="Eggplant", size=large, price=7.95)
sssteak = Sub(sub="Steak", size=large, price=7.95)
sssc = Sub(sub="Steak + Cheese", size=large, price=8.50)
spo = Sub(sub="Sausage, Pepper & Onions", size=large, price=8.50)
sshamburger = Sub(sub="Hamburger", size=large, price=6.95)
sschburger = Sub(sub="Cheeseburger", size=large, price=7.45)
ssfriedchick = Sub(sub="Fried Chicken", size=large, price=8.50)
ssveggie = Sub(sub="Veggie", size=large, price=8.50)
ssc.save()
ssi.save()
sshc.save()
ssm.save()
sstuna.save()
ssturkey.save()
sschick.save()
ssegg.save()
sssteak.save()
sssc.save()
spo.save()
sshamburger.save()
sschburger.save()
ssfriedchick.save()
ssveggie.save()
