#exec(open('orders/createDB.py').read())
ssc = Sub(sub="Cheese", size=small, price=6.50)
ssi = Sub(sub="Italian", size=small, price=6.50)
sshc = Sub(sub="Ham + Cheese", size=small, price=6.50)
ssm = Sub(sub="Meatball", size=small, price=6.50)
sstuna = Sub(sub="Tuna", size=small, price=6.50)
ssturkey = Sub(sub="Turkey", size=small, price=7.50)
sschick = Sub(sub="Chicken Parmigiana", size=small, price=7.50)
ssegg = Sub(sub="Eggplant", size=small, price=6.50)
sssteak = Sub(sub="Steak", size=small, price=6.50)
sssc = Sub(sub="Steak + Cheese", size=small, price=6.95)
sshamburger = Sub(sub="Hamburger", size=small, price=4.60)
sschburger = Sub(sub="Cheeseburger", size=small, price=5.10)
ssfriedchick = Sub(sub="Fried Chicken", size=small, price=6.95)
ssveggie = Sub(sub="Veggie", size=small, price=6.95)
ssc.save()
ssi.save()
sshc.save()
ssm.save()
sstuna.save()
ssturkey.save()
sschick.save()
ssegg.save()
sssteak.save()
sssc.save()
sshamburger.save()
sschburger.save()
ssfriedchick.save()
ssveggie.save()
pmoz = Pasta(pasta="Baked Ziti w/Mozzarella", price=6.50)
pmeat = Pasta(pasta="Baked Ziti w/Meatballs", price=8.75)
pchick = Pasta(pasta="Baked Ziti w/Chicken", price=9.75)
pmoz.save()
pmeat.save()
pchick.save()
saladGarden = Salad(salad="Garden Salad", price=6.25)
saladGreek = Salad(salad="Greek Salad", price=8.25)
saladAnti = Salad(salad="Antipasto", price=8.25)
saladTuna = Salad(salad="Tuna", price=8.25)
saladAnti.save()
saladGarden.save()
saladGreek.save()
saladTuna.save()
dpsGarden = Platter(platter="Garden Salad", size=small, price=35)
dpsGreek = Platter(platter="Greek Salad", size=small, price=45)
dpsAntipasto = Platter(platter="Antipasto", size=small, price=45)
dpsBakedZiti = Platter(platter="Baked Ziti", size=small, price=35)
dpsMeatball = Platter(platter="Meatball Parm", size=small, price=45)
dpsChick = Platter(platter="Chicken Parm", size=small, price=45)
dpsGarden.save()
dpsGreek.save()
dpsAntipasto.save()
dpsBakedZiti.save()
dpsMeatball.save()
dpsChick.save()
dplGarden = Platter(platter="Garden Salad", size=large, price=60)
dplGreek = Platter(platter="Greek Salad", size=large, price=70)
dplAntipasto = Platter(platter="Antipasto", size=large, price=70)
dplBakedZiti = Platter(platter="Baked Ziti", size=large, price=60)
dplMeatball = Platter(platter="Meatball Parm", size=large, price=70)
dplChick = Platter(platter="Chicken Parm", size=large, price=80)
dplGarden.save()
dplGreek.save()
dplAntipasto.save()
dplBakedZiti.save()
dplMeatball.save()
dplChick.save()