# Generated by Django 2.0.3 on 2018-11-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181105_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizzaToppings',
            field=models.ManyToManyField(blank=True, related_name='pizza_toppings', to='orders.PizzaTopping'),
        ),
        migrations.AddField(
            model_name='sub',
            name='subExtra',
            field=models.ManyToManyField(blank=True, related_name='sub_extra', to='orders.SubExtra'),
        ),
    ]
