# Generated by Django 2.0.3 on 2018-11-11 08:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic=False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_orders_checkedout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]