# Generated by Django 2.0.3 on 2018-11-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181105_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='platter',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salad',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sub',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subextra',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
