# Generated by Django 2.0.3 on 2018-11-08 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20181105_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ManyToManyField(blank=True, related_name='order_pizza', to='orders.Pizza')),
                ('platter', models.ManyToManyField(blank=True, related_name='order_platter', to='orders.Platter')),
                ('salad', models.ManyToManyField(blank=True, related_name='order_salad', to='orders.Salad')),
                ('sub', models.ManyToManyField(blank=True, related_name='order_sub', to='orders.Sub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
